name: SimpleFaction
authors: [fernanACM, Ayzrix]
description: SimpleFaction plugin
version: 2.0.0-ACM
main: Ayzrix\SimpleFaction\Main
softdepend: [EconomyAPI]
api: [5.3.0]

permissions:
  simplefaction.cmd:
    default: true
  simplefaction.admin:
    default: op